# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/TUD/Vivado_Projects/CE/pico32_template/pico32.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/TUD/Vivado_Projects/CE/pico32_template/pico32.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/TUD/Vivado_Projects/CE/pico32_template/pico32.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6.xci
# IP: The module: 'design_1_axi_bram_ctrl_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/TUD/Vivado_Projects/CE/pico32_template/pico32.gen/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_6/design_1_axi_bram_ctrl_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_bram_ctrl_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
